### ISSUE TITLE
Is it working or what?

### ISSUE THREAD

**Issue by stdex** [TossShinHwa/CMS#10]
1) /CMS/client/public/Common/ should be /CMS/client/public/common/

2) If I want to edit article:
Why I can't edit article in admin panel?
Why if I click edit in front-end (in article), it's open admin panel, but it's not load data?

I see 2 request in debug:
> Remote Address:127.0.0.1:30002
Request URL:http://localhost:30002/oData/articles/undefined
Request Method:OPTIONS
Status Code:204 No Content

> Remote Address:127.0.0.1:30002
Request URL:http://localhost:30002/oData/articles/undefined
Request Method:GET
Status Code:404 Not Found

3) I think that in config.dev.coffee should be:
img: 'localhost:30001' or img: 'localhost:30000' against img: 'localhost:30002' 
Or you use cache server for images?

4) I have 2 comments in first article (Test Article), but in counter I see  "0 Comments"

5) If I try to add comment, but it's not working for me:

> Remote Address:127.0.0.1:30002
Request URL:http://localhost:30002/oData/articles/add-comment
Request Method:OPTIONS
Status Code:204 No Content 

> Remote Address:127.0.0.1:30002
Request URL:http://localhost:30002/oData/articles/add-comment
Request Method:POST
Status Code:404 Not Found
Request Payload: {"author":{"name":"Administrator","email":null},"content":"dddd","date":"2015-05-08T10:

6) How to edit gallery? How to upload images to gallery?

7) 1s load frontend, 2-3s load admin-panel. It's normal?

**Comment by TossShinHwa** [comment]
Thank you for feedback.

1) You are right, the path should be lowercase and I edited it few day age. Please use `git pull`for update. ([PATH](https://github.com/TossShinHwa/CMS/tree/master/client/public))

2) Maybe it's a mistake, I will check it later.

3) The images server is same as api server for now. I want to move it to cache server, but not yet. Because it's need  some API for cache server to upload files. But I will when I free.

4) I will check it ASAP.

5) I will check it ASAP.

6)  Step:
1. Create a new gallery, then will show a tabs. 
2. Click photos on tabs.
3. Click button named `upload` on right side.
4. Drop images to box.
5. Save.

7) On debug mode, it's will be a little slowly because of it will load many files. It's will faster on release mode. try `grunt - release` to use `release mode`.

**Comment by TossShinHwa** [comment]
Fixed 2, 4, 5.
